<a href="https://colab.research.google.com/github/Vishnup211/American-Express-Data-Analysis/blob/main/American_Express.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [49]:
tf.__version__

'2.17.0'

# Importing Dataset

In [50]:
dataset=pd.read_csv('/content/Dataset_master.xlsx - American Express User Exit Pred.csv')

In [51]:
x=dataset.iloc[:,0:-1].values
y=dataset.iloc[:,-1].values

In [52]:
print(x)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


## Encoding Categorical Data

### Gender coloumn: Label Encoding

In [53]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
x[:,2]=label_encoder.fit_transform(x[:,2])

In [54]:
print(x)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


### Geography coloumn: One hot Encoding

In [55]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [56]:
x[2]

array([0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501], dtype=object)

In [57]:
print(x)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


## Splitting Dataset into Training & Test set

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

### Feature Scaling

In [59]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

# ANN

## Initilazation

In [60]:
ann=tf.keras.models.Sequential()

In [61]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


### Adding second hidden Layer

In [62]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


### Adding output Layer

In [63]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


## ANN TRAINING

### Training on training dataset

Compiling ANN

In [64]:
ann.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])


In [65]:
ann.fit(x_train, y_train, batch_size=32, epochs=120)

Epoch 1/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7131 - loss: 0.6109
Epoch 2/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8034 - loss: 0.4661
Epoch 3/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8076 - loss: 0.4427
Epoch 4/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8140 - loss: 0.4285
Epoch 5/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8110 - loss: 0.4263
Epoch 6/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8219 - loss: 0.4078
Epoch 7/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8248 - loss: 0.4020
Epoch 8/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8232 - loss: 0.4127
Epoch 9/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8246 - loss: 0.4038
Epoch 10/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8314 - loss: 0.3970
Epoch 11/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8370 - loss: 0.3887
Epoch 12/120
249/249 ━━━━━━━━━━━━━━━━━━━━

## Predictions

## Single Predictions

In [68]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
[[False]]


### Prediction on testset

In [69]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


### Confusion Matrix

In [70]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1507   66]
 [ 223  190]]


0.8544813695871097